### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sort'

### ISSUE THREAD

**Issue by 0xrushi** [EvilPort2/SimpleGestureRecognition#1]
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\h4x3d\Downloads\Compressed\SimpleGestureRecognition-master\SimpleGestureRecognition-master\gesture_action.py 

Traceback (most recent call last):
  File "C:\Users\h4x3d\Downloads\Compressed\SimpleGestureRecognition-master\SimpleGestureRecognition-master\gesture_action.py", line 238, in <module>
    gesture_action()
  File "C:\Users\h4x3d\Downloads\Compressed\SimpleGestureRecognition-master\SimpleGestureRecognition-master\gesture_action.py", line 99, in gesture_action
    cnts = contour_area_sort(cnts, 350)
  File "C:\Users\h4x3d\Downloads\Compressed\SimpleGestureRecognition-master\SimpleGestureRecognition-master\gesture_action.py", line 21, in contour_area_sort
    contours.sort(key = cv2.contourArea, reverse = True)
AttributeError: 'NoneType' object has no attribute 'sort'
>>>

**Comment by EvilPort2** [comment]
Is there a way to reproduce the problem? I ran the program right now but there were no problems. Did you install imutils and all other dependencies. Also I see that you are using Python 2.7. Perhaps that is the reason why you are facing this problem. Try running the program in Python 3

**Comment by 0xrushi** [comment]
oh , but i heard opencv is not made efficient for python3.
Im searching this code for python2,Anyways if you dont know ,close this issue.

**Comment by EvilPort2** [comment]
At first this program was built for Python 2. But after a few days OpenCV 2 was updated to OpenCV 3. That is why I had to move to Python 3 because OpenCV 3 had a lot of problems with Python 2. Hope that Python 3 runs the program well.
