### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TwincyZatakia** [EvilPort2/SimpleGestureRecognition#3]
===== RESTART: C:/Python/Python36-32/boo/twinct trail/gesture_action.py =====
(14, 54, 220, 44, 162, 255)
0 0 0
Traceback (most recent call last):
  File "C:/Python/Python36-32/boo/twinct trail/gesture_action.py", line 262, in <module>
    gesture_action()
  File "C:/Python/Python36-32/boo/twinct trail/gesture_action.py", line 88, in gesture_action
    imgHSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11178: error: (-215) (scn == 3 || scn == 4) && (depth == 0 || depth == 5) in function cv::cvtColor

**Comment by TwincyZatakia** [comment]
can you tell me why this error coming I'm using python 3.6

**Comment by EvilPort2** [comment]
Clone the repo once again. I hope the error should be fixed.

**Comment by TwincyZatakia** [comment]
repo??

**Comment by TwincyZatakia** [comment]
yeah letme try

**Comment by TwincyZatakia** [comment]
Traceback (most recent call last):
  File "C:\Users\dhruv\Downloads\SimpleGestureRecognition-master\SimpleGestureRecognition-master\code\gesture_action.py", line 262, in <module>
    gesture_action()
same error

**Comment by EvilPort2** [comment]
download the repo again. or clone it. the bug has been fixed

**Comment by TwincyZatakia** [comment]
thank you so much it worked but output is not coming its giving only zero as the output i have done the range detector part but still it is not detecting yellow color

**Comment by TwincyZatakia** [comment]
===== RESTART: C:/Python/Python36-32/boo/new /gesture_action.py 
(14, 54, 220, 44, 162, 255)
0 0 0
0 0 0

**Comment by TwincyZatakia** [comment]
??
